name: Welcomer
version: "${project.version}"
main: com.MoustafaKaribou.welcomer.MonPlugin
api-version: "26.1.2"
author: MoustafaKaribou
description: A plugin that allows sending a welcome message to each player, and a code of conduct message for new players.

# Déclaration des commandes (doit correspondre au code Java)
commands:
  hello:
    description: Send a welcome message to the player.
    usage: /hello

# Déclaration des permissions (optionnel, exemple)
permissions:
  Welcomer.hello:
    description: Allows the use of the /hello command.
    default: true
