name: KaribouWelcome
version: "${project.version}"
main: com.KaribouDev.KaribouWelcome.KaribouWelcome
api-version: "26.1.2"
author: MoustafaKaribou
description: A plugin that allows sending a welcome message to each player, and a code of conduct message for new players.

commands:
  rules:
    description: Send the rules of the server to the player.
    usage: /rules
    permission: karibouwelcome.rules

  karibouwelcome:
    description: Manage KaribouWelcome.
    usage: /karibouwelcome <reload|test>
    aliases:
      - kbw

permissions:
  karibouwelcome.rules:
    description: Allows the use of the /rules command.
    default: true

  karibouwelcome.reload:
    description: Allows reloading the plugin configuration.
    default: op

  karibouwelcome.test:
    description: Test configured messages.
    default: op